# Site settings
title: 
header-img: img/home-bg.png
email: anukhambete@gmail.com
copyright_name: anukhambete
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  anukhambete
learn_profile: anukhambete
email_username: anukhambete@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
